controllers:
    config:
        joints:
            state: joint_states
            setpoint: joint_setpoint
            command: joint_command
            cascaded_position: False
            dynamic_reconfigure: False
    x:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    y:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    z:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    pitch:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100} 
    roll:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    yaw:
        velocity: {p: 150, i: 100, d: 0}
        position: {p: 100, i: 5, d: 100}
    rudder_joint:
        velocity: {p: 5.0, i: 1, d: 0.0}
        position: {p: 10.0, i: 1, d: 0}
    sail_joint:
        velocity: {p: 5.0, i: 1, d: 0.0}
        position: {p: 10, i: 1, d: 0}

training: #namespace
    task_and_robot_environment_name: 'Sailboat-v0'
    ros_ws_abspath: "/home/courtney/catkin_ws" # TODO change this depending on the computer being used
    
    #ddpg parameters
    buffer_size: 1000000
    batch_size: 64
    gamma: 0.9
    tau: 0.001
    lr_actor: 0.00001
    lr_critic: 0.001

    hidden_size1: 400
    hidden_size2: 300

    buffer_start: 100
    epsilon: 1
    epsilon_decay: 0
    eta: 1
    eta_decay: 0.7

    print_every: 10

    nepisodes: 5000
    nsteps: 1000
    
